apiVersion: v1
kind: Service
metadata:
    labels:
        service: backend-feed
    name: backend-feed
spec:
    ports:
    # - name: "8001"
    - name: "8080"
      # port: 8001
      port: 8080
      # targetPort: 8001
      targetPort: 8080
      protocol: TCP
    selector:
        # service: backend-feed
        run: backend-feed