# apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    # service: reverseproxy
    run: reverseproxy
spec:
  replicas: 2
  # replicas: 1
  selector:
    matchLabels:
      # service: reverseproxy
      app: reverseproxy
  template:
    metadata:
      labels:
        # service: reverseproxy
        app: reverseproxy
    spec:
      containers:
      - image: tugboatstrike/udagram-reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            # memory: "1024Mi"
            memory: "2048Mi"
            cpu: "500m"   
        ports:
        # - containerPort: 8001
        - containerPort: 8080
      restartPolicy: Always