apiVersion: v1
kind: Service
metadata:
    labels:
        service: reverseproxy
    name: reverseproxy
spec:
    ports:
    #- name: "8001"
    #  port: 8001
    #  targetPort: 8001
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
        service: reverseproxy